### ISSUE TITLE
[Bug] Sticky window leaves unusable region after minimization

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-epoch#1781]
**Issue/Description:**
When a sticky window is minimized in COSMIC Desktop, the screen area previously occupied by the window becomes unresponsive. Any UI controls or elements from other windows located in that region are not accessible via mouse interaction, making the space effectively unusable.

**Version:**
```
cosmic-session:
  Installed: 0.1.0~1743784951~24.04~bbd803e

 cosmic-comp:
  Installed: 0.1~1743798792~24.04~99bbd10
```

**Steps to Reproduce:**
- Open a window & make it sticky window 
- Move or resize it to cover a region of the screen
- Minimize the sticky window
- Attempt to interact with elements of another window located underneath the previously occupied region

**Expected Behavior:**
The region where the sticky window was located should be fully usable after the window is minimized. Controls underneath should be accessible as normal.

**Other Notes:**

https://github.com/user-attachments/assets/8c31a40d-eead-45dd-9d7c-5e5a7c230dbd
